### ISSUE TITLE
可以提供数据库脚本吗

### ISSUE THREAD

**Issue by liubo988** [cloudfavorites/favorites-web#7]
我想本地跑一下项目，可以把数据库脚本文件发下吗 谢谢啦！

**Comment by ityouknow** [comment]
jpa技术是不需要脚本的，项目运行后脚本会自动创建。

**Comment by liubo988** [comment]
嗯 之前不了解 谢谢 ，生成脚本了本地。还有个问题，redis我现在想禁用 。怎么修改配置文件？

**Comment by feitian124** [comment]
@ityouknow 你是不是有一些种子数据呢，项目跑起来进首页就报错。
#14 出错应该也是这个原因：
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[na:1.8.0_131]
	at java.util.ArrayList.get(ArrayList.java:429) ~[na:1.8.0_131]
	at com.favorites.repository.impl.CollectorRepositoryImpl.getMostFollowedUser(CollectorRepositoryImpl.java:44) ~[main/:na]

**Comment by ityouknow** [comment]
我找时间看一下。

**Comment by ityouknow** [comment]
使用最新代码，问题已经解决。@	liubo988
